### ISSUE TITLE
request for 7b01d5c6d1bb411d1aa0b83504bd32d155f2bd23

### ISSUE THREAD

**Issue by drdamour** [webjars/hal-browser#4]
request a jar for commit 7b01d5c6d1bb411d1aa0b83504bd32d155f2bd23

the latest has a significant bug doc'd at https://github.com/mikekelly/hal-browser/issues/79 and https://github.com/mikekelly/hal-browser/issues/62 would like to get this one as a sensible working point

**Comment by drdamour** [comment]
@jamesward i confirmed that vendor exclusion breaks the hal-browser

**Comment by jamesward** [comment]
Usually external dependencies are specified as dependencies in the Maven metadata.  But sometimes this doesn't work depending on how they are loaded.  If this approach will work with this library then can you send a PR or post a comment with the necessary deps.  Otherwise we can add them back.

**Comment by drdamour** [comment]
the way the libs are loaded i think we need to include the vendor dir, can
you update please?
